List<integer>  listInteger = new List<Integer>();
listInteger.add(10);
listInteger.add(15);
listInteger.add(21);
listInteger.add(15);
listInteger.add(15);
//CalculatorSt.add(listInteger);

CalculatorSt.add(listInteger);



// sum = sum + eachInt
 //    =  0 +  eachTime value 




CalculatorSt ct=new CalculatorSt();

integer sum1=CalculatorSt.add(5,15);
system.debug(sum1);

integer sum2=CalculatorSt.add(5,15,25);
system.debug(sum2);

